import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar";
export default function Contact() {
  return (
    <div>
      <Head>
        <title>Aditya Sai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h1>Resume</h1>
      <br />
      <br />
      <div className="h-screen flex items-center justify-center">
        <iframe
          src="https://drive.google.com/file/d/1WB8dQLuuaLmbPOvq5s8k9JMTlYAZgcwj/preview"
          width="640"
          height="480"
          allow="autoplay"
        ></iframe>
      </div>
    </div>
  );
}
